### ISSUE TITLE
对话模式不可用

### ISSUE THREAD

**Issue by Sunshine-X** [bilibili-ayang/bob-plugin-free-chatgpt#2]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43695246/223033724-b69a11c1-63d3-44b0-93f4-42811c0e1a2c.png">
除了第一次可对话，无论输入什么都是这样。

**Comment by Sunshine-X** [comment]
需要清除后再次对话。看文档.jpg

**Comment by bilibili-ayang** [comment]
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/43695246/223033724-b69a11c1-63d3-44b0-93f4-42811c0e1a2c.png">
> 
> 除了第一次可对话，无论输入什么都是这样。

感谢反馈，问题解决过，需要更新一下哦！
