### ISSUE TITLE
Translate Mode Issue when text is related to ChatGPT

### ISSUE THREAD

**Issue by Kyle-Ye** [bilibili-ayang/bob-plugin-free-chatgpt#3]
Even in translation mode, ChatGPT does not choose to translate texts about ChatGPT but instead provides a response similar to a conversation mode.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/43724855/223910663-9b2771cb-c0df-4763-9f22-8ecb28f2c7f1.png">

**Comment by bilibili-ayang** [comment]
> Even in translation mode, ChatGPT does not choose to translate texts about ChatGPT but instead provides a response similar to a conversation mode.
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/43724855/223910663-9b2771cb-c0df-4763-9f22-8ecb28f2c7f1.png">

感谢反馈，我这边修复一下！

**Comment by bilibili-ayang** [comment]
> Even in translation mode, ChatGPT does not choose to translate texts about ChatGPT but instead provides a response similar to a conversation mode.
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/43724855/223910663-9b2771cb-c0df-4763-9f22-8ecb28f2c7f1.png">

此问题已修复，从 app 检查更新或者点击链接下载 [v0.1.2](https://github.com/bilibili-ayang/bob-plugin-free-chatgpt/releases/download/v0.1.2/bob-plugin-free-chatgpt.bobplugin)
